package:
  name: pysym
  version: 0.3.0.git

source:
  path: ../

build:
  number: 0

requirements:
  build:
    - python
  run:
    - python

test:
  imports:
    - pysym

  requires:
    - pytest

  # commands:
  #   - py.test --pyargs pysym

about:
  home: https://github.com/bjodah/pysym
  license: BSD
  summary: Minimal symbolic manipulation framework
