package:
    name: pysym
    version: 0.1.0.dev0

source:
    path: ../

build:
    number: 0

requirements:
    build:
        - python
        - cython
    run:
        - python

test:
    imports:
        - pysym

    requires:
        - pytest

    commands:
        - py.test --pyargs pysym

about:
    home: https://github.com/bjodah/pysym
    license: BSD
    summary: Minimal symbolic manipulation framework
